Repository RankyList/ranky-list, pull requests merged in 2022-11, with the labels that each got.

#2 Add first documentation and issue/PR templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/config.yml
  .github/pull_request_template.md
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/logo.ico
Labels: documentation, templating

#3 Add security policy and fix some typos
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/question.yml
  CONTRIBUTING.md
  README.md
  SECURITY.md
Labels: documentation

#10 [DOCUMENTATION] Update CONTRIBUTING for branch changes
  CONTRIBUTING.md
Labels: documentation

#17 Added base theme
  .gitignore
  svelte-kit/src/app.html
  svelte-kit/src/app.postcss
  svelte-kit/src/lib/components/Button.svelte
  svelte-kit/src/routes/+layout.svelte
  svelte-kit/src/routes/+page.server.ts
  svelte-kit/src/routes/+page.svelte
  svelte-kit/src/theme.postcss
  svelte-kit/static/favicon.ico
  svelte-kit/static/favicon.png
  svelte-kit/static/logo.png
  svelte-kit/static/original-logo.png
Labels: front, templating
